// Code generated by protoc-gen-go. DO NOT EDIT.
// source: failover.proto

/*
Package failover is a generated protocol buffer package.

It is generated from these files:
	failover.proto

It has these top-level messages:
	Empty
	HealthCheckResponse
	PauseRequest
	PauseResponse
	ResumeResponse
*/
package failover

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HealthCheckResponse_Status int32

const (
	HealthCheckResponse_UNKNOWN   HealthCheckResponse_Status = 0
	HealthCheckResponse_HEALTHY   HealthCheckResponse_Status = 1
	HealthCheckResponse_UNHEALTHY HealthCheckResponse_Status = 2
)

var HealthCheckResponse_Status_name = map[int32]string{
	0: "UNKNOWN",
	1: "HEALTHY",
	2: "UNHEALTHY",
}
var HealthCheckResponse_Status_value = map[string]int32{
	"UNKNOWN":   0,
	"HEALTHY":   1,
	"UNHEALTHY": 2,
}

func (x HealthCheckResponse_Status) String() string {
	return proto.EnumName(HealthCheckResponse_Status_name, int32(x))
}
func (HealthCheckResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 0}
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type HealthCheckResponse struct {
	Status HealthCheckResponse_Status `protobuf:"varint,1,opt,name=status,enum=failover.HealthCheckResponse_Status" json:"status,omitempty"`
}

func (m *HealthCheckResponse) Reset()                    { *m = HealthCheckResponse{} }
func (m *HealthCheckResponse) String() string            { return proto.CompactTextString(m) }
func (*HealthCheckResponse) ProtoMessage()               {}
func (*HealthCheckResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HealthCheckResponse) GetStatus() HealthCheckResponse_Status {
	if m != nil {
		return m.Status
	}
	return HealthCheckResponse_UNKNOWN
}

type PauseRequest struct {
	Timeout int64 `protobuf:"varint,1,opt,name=timeout" json:"timeout,omitempty"`
	Expiry  int64 `protobuf:"varint,2,opt,name=expiry" json:"expiry,omitempty"`
}

func (m *PauseRequest) Reset()                    { *m = PauseRequest{} }
func (m *PauseRequest) String() string            { return proto.CompactTextString(m) }
func (*PauseRequest) ProtoMessage()               {}
func (*PauseRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PauseRequest) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *PauseRequest) GetExpiry() int64 {
	if m != nil {
		return m.Expiry
	}
	return 0
}

type PauseResponse struct {
	CreatedAt *google_protobuf.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	ExpiresAt *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt" json:"expires_at,omitempty"`
}

func (m *PauseResponse) Reset()                    { *m = PauseResponse{} }
func (m *PauseResponse) String() string            { return proto.CompactTextString(m) }
func (*PauseResponse) ProtoMessage()               {}
func (*PauseResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PauseResponse) GetCreatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *PauseResponse) GetExpiresAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.ExpiresAt
	}
	return nil
}

type ResumeResponse struct {
	CreatedAt *google_protobuf.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
}

func (m *ResumeResponse) Reset()                    { *m = ResumeResponse{} }
func (m *ResumeResponse) String() string            { return proto.CompactTextString(m) }
func (*ResumeResponse) ProtoMessage()               {}
func (*ResumeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ResumeResponse) GetCreatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "failover.Empty")
	proto.RegisterType((*HealthCheckResponse)(nil), "failover.HealthCheckResponse")
	proto.RegisterType((*PauseRequest)(nil), "failover.PauseRequest")
	proto.RegisterType((*PauseResponse)(nil), "failover.PauseResponse")
	proto.RegisterType((*ResumeResponse)(nil), "failover.ResumeResponse")
	proto.RegisterEnum("failover.HealthCheckResponse_Status", HealthCheckResponse_Status_name, HealthCheckResponse_Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Failover service

type FailoverClient interface {
	HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	Pause(ctx context.Context, in *PauseRequest, opts ...grpc.CallOption) (*PauseResponse, error)
	Resume(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ResumeResponse, error)
}

type failoverClient struct {
	cc *grpc.ClientConn
}

func NewFailoverClient(cc *grpc.ClientConn) FailoverClient {
	return &failoverClient{cc}
}

func (c *failoverClient) HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := grpc.Invoke(ctx, "/failover.Failover/health_check", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *failoverClient) Pause(ctx context.Context, in *PauseRequest, opts ...grpc.CallOption) (*PauseResponse, error) {
	out := new(PauseResponse)
	err := grpc.Invoke(ctx, "/failover.Failover/pause", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *failoverClient) Resume(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ResumeResponse, error) {
	out := new(ResumeResponse)
	err := grpc.Invoke(ctx, "/failover.Failover/resume", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Failover service

type FailoverServer interface {
	HealthCheck(context.Context, *Empty) (*HealthCheckResponse, error)
	Pause(context.Context, *PauseRequest) (*PauseResponse, error)
	Resume(context.Context, *Empty) (*ResumeResponse, error)
}

func RegisterFailoverServer(s *grpc.Server, srv FailoverServer) {
	s.RegisterService(&_Failover_serviceDesc, srv)
}

func _Failover_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FailoverServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/failover.Failover/HealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FailoverServer).HealthCheck(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Failover_Pause_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FailoverServer).Pause(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/failover.Failover/Pause",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FailoverServer).Pause(ctx, req.(*PauseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Failover_Resume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FailoverServer).Resume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/failover.Failover/Resume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FailoverServer).Resume(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Failover_serviceDesc = grpc.ServiceDesc{
	ServiceName: "failover.Failover",
	HandlerType: (*FailoverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "health_check",
			Handler:    _Failover_HealthCheck_Handler,
		},
		{
			MethodName: "pause",
			Handler:    _Failover_Pause_Handler,
		},
		{
			MethodName: "resume",
			Handler:    _Failover_Resume_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "failover.proto",
}

func init() { proto.RegisterFile("failover.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 356 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x91, 0x4d, 0x4b, 0xfb, 0x40,
	0x10, 0xc6, 0x9b, 0xfe, 0x69, 0xda, 0x4e, 0x5f, 0xfe, 0x65, 0x85, 0x1a, 0x02, 0xa2, 0x2c, 0x1e,
	0x3c, 0xa5, 0x58, 0xf1, 0xa0, 0x78, 0x68, 0x91, 0x4a, 0xa1, 0x12, 0x25, 0xb6, 0x88, 0xa7, 0xb2,
	0xad, 0xd3, 0x17, 0x6c, 0xdc, 0x98, 0xdd, 0x88, 0xfd, 0x00, 0xfa, 0xb5, 0xfc, 0x6a, 0x92, 0xcd,
	0xa6, 0x55, 0x2a, 0x7a, 0xf1, 0xf8, 0xcc, 0x3e, 0xcf, 0xec, 0xcc, 0x6f, 0xa0, 0x3a, 0x61, 0xf3,
	0x05, 0x7f, 0xc6, 0xd0, 0x09, 0x42, 0x2e, 0x39, 0x29, 0xa4, 0xda, 0xde, 0x9d, 0x72, 0x3e, 0x5d,
	0x60, 0x43, 0xd5, 0x47, 0xd1, 0xa4, 0x21, 0xe7, 0x3e, 0x0a, 0xc9, 0xfc, 0x20, 0xb1, 0xd2, 0x3c,
	0xe4, 0x3a, 0x7e, 0x20, 0x97, 0xf4, 0xcd, 0x80, 0xad, 0x2e, 0xb2, 0x85, 0x9c, 0x9d, 0xcf, 0x70,
	0xfc, 0xe0, 0xa1, 0x08, 0xf8, 0xa3, 0x40, 0x72, 0x06, 0xa6, 0x90, 0x4c, 0x46, 0xc2, 0x32, 0xf6,
	0x8c, 0x83, 0x6a, 0x73, 0xdf, 0x59, 0x7d, 0xf6, 0x8d, 0xdd, 0xb9, 0x51, 0x5e, 0x4f, 0x67, 0xe8,
	0x21, 0x98, 0x49, 0x85, 0x94, 0x20, 0x3f, 0x70, 0x7b, 0xee, 0xd5, 0xad, 0x5b, 0xcb, 0xc4, 0xa2,
	0xdb, 0x69, 0x5f, 0xf6, 0xbb, 0x77, 0x35, 0x83, 0x54, 0xa0, 0x38, 0x70, 0x53, 0x99, 0xa5, 0x2d,
	0x28, 0x5f, 0xb3, 0x48, 0xa0, 0x87, 0x4f, 0x11, 0x0a, 0x49, 0x2c, 0xc8, 0xc7, 0x43, 0xf3, 0x48,
	0xaa, 0x09, 0xfe, 0x79, 0xa9, 0x24, 0x75, 0x30, 0xf1, 0x25, 0x98, 0x87, 0x4b, 0x2b, 0xab, 0x1e,
	0xb4, 0xa2, 0xaf, 0x06, 0x54, 0x74, 0x0b, 0xbd, 0xc4, 0x09, 0xc0, 0x38, 0x44, 0x26, 0xf1, 0x7e,
	0xc8, 0x92, 0x36, 0xa5, 0xa6, 0xed, 0x24, 0x6c, 0x9c, 0x94, 0x8d, 0xd3, 0x4f, 0xd9, 0x78, 0x45,
	0xed, 0x6e, 0xcb, 0x38, 0xaa, 0xda, 0xa2, 0x88, 0xa3, 0xd9, 0xdf, 0xa3, 0xda, 0xdd, 0x96, 0xb4,
	0x07, 0x55, 0x0f, 0x45, 0xe4, 0xff, 0xc5, 0x1c, 0xcd, 0x77, 0x03, 0x0a, 0x17, 0x9a, 0x3c, 0x69,
	0x41, 0x79, 0xa6, 0xe0, 0x0f, 0xc7, 0x31, 0x7d, 0xf2, 0x7f, 0x7d, 0x14, 0x75, 0x4d, 0x7b, 0xe7,
	0xc7, 0x2b, 0xd1, 0x0c, 0x39, 0x85, 0x5c, 0x10, 0x23, 0x22, 0xf5, 0xb5, 0xf3, 0x33, 0x76, 0x7b,
	0x7b, 0xa3, 0xbe, 0xca, 0x1e, 0x83, 0x19, 0xaa, 0xbd, 0x36, 0xff, 0xb5, 0xd6, 0x85, 0xaf, 0xab,
	0xd3, 0xcc, 0xc8, 0x54, 0x0b, 0x1e, 0x7d, 0x04, 0x00, 0x00, 0xff, 0xff, 0xbb, 0x96, 0x35, 0xd1,
	0xae, 0x02, 0x00, 0x00,
}
