{
 "title": "stolon-keeper",
 "tags": [
  "postgres",
  "stolon"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(stolon_cluster_identifier, cluster_name)"
   },
   { "name": "interval", "label": "interval", "query": "1m,5m,15m" }
  ]
 },
 "panels": [
  {
   "title": "Keeper Statuses",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "# Join metrics into a flat table of values per instance (instance, role, target_role, last_sync_success)\nmax by (instance, target_role, role) (\n  stolon_cluster_identifier{cluster_name=\"$cluster\"} * on (instance) group_left(target_role, role) (\n    time() - stolon_keeper_last_sync_success_seconds * on(instance) group_left(target_role, role) (\n      (stolon_keeper_local_role == 1) * on(instance) group_left(role, target_role) (\n        label_replace(stolon_keeper_target_role == 1, \"target_role\", \"$1\", \"role\", \"(.*)\")\n      )\n    )\n  )\n)"
    }
   ]
  },
  {
   "title": "PgBouncer active connections",
   "type": "graph",
   "description": "Number of client connections that are active via the PgBouncers.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (pgbouncer_pools_client_active_connections and on (instance) (stolon_cluster_identifier{cluster_name=\"$cluster\"} and on (instance) stolon_keeper_shutdown_seconds))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Time since last successful sync",
   "type": "graph",
   "description": "Tracks the time passed since the last PgBouncer reload. We expect stolon-pgbouncer to periodically reload PgBouncer, so this has exceeded the store poll interval then we know PgBouncer reloading is failing.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - ((stolon_keeper_last_sync_success_seconds > 0) and ignoring(cluster_name) stolon_cluster_identifier{cluster_name=\"$cluster\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Last valid clusterdata",
   "type": "graph",
   "description": "Tracks time passed since last saw a valid clusterdata value. If this rises, you can expect an issue in configuration or communication problems with the store.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - ((stolon_keeper_clusterdata_last_valid_update_seconds > 0) and ignoring(cluster_name) stolon_cluster_identifier{cluster_name=\"$cluster\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}