{
 "title": "stolon-pgbouncer",
 "tags": [
  "stolon",
  "postgresql"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(stolon_pgbouncer_cluster_identifier, cluster_name)"
   },
   { "name": "interval", "label": "interval", "query": "1m,5m,15m" }
  ]
 },
 "panels": [
  {
   "title": "Proxy Statuses",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by (pod_name, cluster_name, store_prefix, keeper) (\n  time() - stolon_pgbouncer_last_reload_seconds * on(pod_name) group_left(cluster_name, store_prefix, keeper) (\n    stolon_pgbouncer_cluster_identifier{cluster_name=\"$cluster\"} != ignoring(cluster_name, store_prefix, keeper) group_left(keeper) stolon_pgbouncer_host_hash\n  )\n)"
    }
   ]
  },
  {
   "title": "PgBouncers Proxy Targets (count per keeper)",
   "type": "graph",
   "description": "stolon-pgbouncer controls a PgBouncer to point at our master Postgres. This graph visualises the number of PgBouncers that are pointed at each keeper. Something is wrong if more than one keeper is being proxied.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count_values by (keeper) (\n  \"__value__\", stolon_pgbouncer_host_hash and ignoring(cluster_name, store_prefix, keeper) stolon_pgbouncer_cluster_identifier{cluster_name=\"$cluster\"}\n)",
     "legendFormat": "{{ keeper }}"
    }
   ]
  },
  {
   "title": "Time since last successful PgBouncer reload",
   "type": "graph",
   "description": "Tracks the time passed since the last PgBouncer reload. We expect stolon-pgbouncer to periodically reload PgBouncer, so this has exceeded the store poll interval then we know PgBouncer reloading is failing.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - ((stolon_pgbouncer_last_reload_seconds > 0) and ignoring(cluster_name, store_prefix) stolon_pgbouncer_cluster_identifier{cluster_name=\"$cluster\"})",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Pending Shutdown Seconds",
   "type": "graph",
   "description": "After receiving a SIGTERM stolon-pgbouncer will wait for PgBouncer to finish serving requests before fully terminating. We expect our termination grace period to be 2hrs which is where we'll terminate our pod regardless of outstanding connections: this is where we set our threshold.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - ((stolon_pgbouncer_shutdown_seconds > 0) and ignoring(cluster_name, store_prefix) stolon_pgbouncer_cluster_identifier{cluster_name=\"$cluster\"})",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  }
 ]
}