{
 "title": "stolon-sentinel",
 "tags": [
  "stolon",
  "postgres"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(stolon_cluster_identifier, cluster_name)"
   },
   { "name": "interval", "label": "interval", "query": "1m,5m,15m" }
  ]
 },
 "panels": [
  {
   "title": "Time since last successful cluster check",
   "type": "graph",
   "description": "Tracks the time passed since the sentinel last successfully processed the sync loop. This implies that the sentinel was the leader.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(time() - stolon_sentinel_last_cluster_check_success_seconds and ignoring(cluster_name, store_prefix) stolon_cluster_identifier{cluster_name=\"$cluster\"}) < 10000000",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Leadership status",
   "type": "graph",
   "description": "Reports whether a sentinel is leader",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "stolon_sentinel_is_leader and on(instance) stolon_cluster_identifier{cluster_name=\"$cluster\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Leadership changes",
   "type": "graph",
   "description": "Whether a sentinel instance has been elected leader",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(stolon_sentinel_leader_count[1m]) and on(instance) stolon_cluster_identifier{cluster_name=\"$cluster\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}