{
 "title": "stolon-proxy",
 "tags": [
  "postgres",
  "stolon"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(stolon_cluster_identifier, cluster_name)"
    }
   },
   { "name": "interval", "label": "interval", "query": "1m,5m,15m" }
  ]
 },
 "panels": [
  {
   "title": "Proxy Statuses",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max(stolon_proxy_health) by(instance)"
    }
   ]
  },
  {
   "title": "Cluster Data Fetch Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(stolon_proxy_get_cluster_info_errors[1m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Cluster Data Update Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(stolon_proxy_update_proxy_info_errors[1m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}